In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv(r"C:\Users\I SKY\Downloads/Nassau Candy Distributor.csv")
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [ ]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Country/Region', 'City', 'State/Province',
       'Postal Code', 'Division', 'Region', 'Product ID', 'Product Name',
       'Sales', 'Units', 'Gross Profit', 'Cost'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  object
 3   Ship Date       10194 non-null  object
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  object
 7   City            10194 non-null  object
 8   State/Province  10194 non-null  object
 9   Postal Code     10194 non-null  object
 10  Division        10194 non-null  object
 11  Region          10194 non-null  object
 12  Product ID      10194 non-null  object
 13  Product Name    10194 non-null  object
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
dtypes: float64(3), int64(3), object(12)
memory usage: 1.4+ MB

In [ ]:
df.isnull().sum()  # No Missing values ..

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Division          0
Region            0
Product ID        0
Product Name      0
Sales             0
Units             0
Gross Profit      0
Cost              0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
# This one line replaces almost all of your previous code!
df['Order Date'] = pd.to_datetime(df['Order Date'], format='mixed', dayfirst=True)

# You can do the same for Ship Date
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='mixed', dayfirst=True)

In [ ]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,2024-01-03,2026-06-30,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,2024-01-05,2026-07-05,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  datetime64[ns]
 3   Ship Date       10194 non-null  datetime64[ns]
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  object
 7   City            10194 non-null  object
 8   State/Province  10194 non-null  object
 9   Postal Code     10194 non-null  object
 10  Division        10194 non-null  object
 11  Region          10194 non-null  object
 12  Product ID      10194 non-null  object
 13  Product Name    10194 non-null  object
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(10)
memory usage: 1.4+ MB

In [ ]:
print(f"Original DataFrame shape: {df.shape}")

# Calculate lead time (difference between Ship Date and Order Date)
df['Lead Time'] = df['Ship Date'] - df['Order Date']

# Filter out rows with negative lead times
df = df[df['Lead Time'] >= pd.Timedelta(0)]

print(f"DataFrame shape after removing negative lead times: {df.shape}")

display(df.head())

Original DataFrame shape: (10194, 18)
DataFrame shape after removing negative lead times: (10194, 19)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost,Lead Time
0,1,US-2021-103800-CHO-MIL-31000,2024-01-03,2026-06-30,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,909 days
1,2,US-2021-112326-CHO-TRI-54000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60,909 days
2,3,US-2021-112326-CHO-NUT-13000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00,909 days
3,4,US-2021-112326-CHO-SCR-58000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30,909 days
4,5,US-2021-141817-CHO-TRI-54000,2024-01-05,2026-07-05,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90,912 days

In [ ]:
factory_data = {
    'Factory': ['Lot\'s O\' Nuts', 'Wicked Choccy\'s', 'Sugar Shack', 'Secret Factory', 'The Other Factory'],
    'Latitude': [32.881893, 32.076176, 48.11914, 41.446333, 35.1175],
    'Longitude': [-111.768036, -81.088371, -96.18115, -90.565487, -89.971107]
}
factory_df = pd.DataFrame(factory_data)

display(factory_df.head())

             Factory   Latitude   Longitude
0      Lot's O' Nuts  32.881893 -111.768036
1    Wicked Choccy's  32.076176  -81.088371
2        Sugar Shack  48.119140  -96.181150
3     Secret Factory  41.446333  -90.565487
4  The Other Factory  35.117500  -89.971107

In [ ]:
product_factory_data = {
    'Division': ['Chocolate', 'Chocolate', 'Chocolate', 'Chocolate', 'Chocolate', 'Sugar', 'Sugar', 'Sugar', 'Sugar', 'Other', 'Sugar', 'Sugar', 'Other', 'Other', 'Other'],
    'Product Name': ['Wonka Bar - Nutty Crunch Surprise', 'Wonka Bar - Fudge Mallows', 'Wonka Bar -Scrumdiddlyumptious', 'Wonka Bar - Milk Chocolate', 'Wonka Bar - Triple Dazzle Caramel', 'Laffy Taffy', 'SweeTARTS', 'Nerds', 'Fun Dip', 'Fizzy Lifting Drinks', 'Everlasting Gobstopper', 'Hair Toffee', 'Lickable Wallpaper', 'Wonka Gum', 'Kazookles'],
    'Factory': ['Lot\'s O\' Nuts', 'Lot\'s O\' Nuts', 'Lot\'s O\' Nuts', 'Wicked Choccy\'s', 'Wicked Choccy\'s', 'Sugar Shack', 'Sugar Shack', 'Sugar Shack', 'Sugar Shack', 'Sugar Shack', 'Secret Factory', 'The Other Factory', 'Secret Factory', 'Secret Factory', 'The Other Factory']
}
product_factory_df = pd.DataFrame(product_factory_data)
display(product_factory_df.head())

    Division                       Product Name          Factory
0  Chocolate  Wonka Bar - Nutty Crunch Surprise    Lot's O' Nuts
1  Chocolate          Wonka Bar - Fudge Mallows    Lot's O' Nuts
2  Chocolate     Wonka Bar -Scrumdiddlyumptious    Lot's O' Nuts
3  Chocolate         Wonka Bar - Milk Chocolate  Wicked Choccy's
4  Chocolate  Wonka Bar - Triple Dazzle Caramel  Wicked Choccy's

In [ ]:
# Merge df with product_factory_df on 'Product Name'
df_merged = pd.merge(df, product_factory_df, on='Product Name', how='left')

# Merge the result with factory_df on 'Factory'
df_merged = pd.merge(df_merged, factory_df, on='Factory', how='left')

display(df_merged.head())
df_merged.shape

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,...,Product Name,Sales,Units,Gross Profit,Cost,Lead Time,Division_y,Factory,Latitude,Longitude
0,1,US-2021-103800-CHO-MIL-31000,2024-01-03,2026-06-30,Standard Class,103800,United States,Houston,Texas,77095,...,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,909 days,Chocolate,Wicked Choccy's,32.076176,-81.088371
1,2,US-2021-112326-CHO-TRI-54000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60,909 days,Chocolate,Wicked Choccy's,32.076176,-81.088371
2,3,US-2021-112326-CHO-NUT-13000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00,909 days,Chocolate,Lot's O' Nuts,32.881893,-111.768036
3,4,US-2021-112326-CHO-SCR-58000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30,909 days,Chocolate,Lot's O' Nuts,32.881893,-111.768036
4,5,US-2021-141817-CHO-TRI-54000,2024-01-05,2026-07-05,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,...,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90,912 days,Chocolate,Wicked Choccy's,32.076176,-81.088371

(10194, 23)

Categorizing Routes by Factory to Customer Region

In [ ]:
factory_region_routes = df_merged.groupby(['Factory', 'Region'])['Order ID'].nunique().reset_index()
factory_region_routes.rename(columns={'Order ID': 'Number of Orders'}, inplace=True)
display(factory_region_routes.head())

          Factory    Region  Number of Orders
0   Lot's O' Nuts  Atlantic              1378
1   Lot's O' Nuts      Gulf               745
2   Lot's O' Nuts  Interior              1113
3   Lot's O' Nuts   Pacific              1524
4  Secret Factory  Atlantic                70

 Categorizing Routes by Factory to Customer State

In [ ]:
factory_state_routes = df_merged.groupby(['Factory', 'State/Province'])['Order ID'].nunique().reset_index()
factory_state_routes.rename(columns={'Order ID': 'Number of Orders'}, inplace=True)
display(factory_state_routes.head())

         Factory    State/Province  Number of Orders
0  Lot's O' Nuts           Alabama                30
1  Lot's O' Nuts           Alberta                12
2  Lot's O' Nuts           Arizona                94
3  Lot's O' Nuts          Arkansas                25
4  Lot's O' Nuts  British Columbia                18

Shipments by Ship Mode

In [ ]:
shipments_by_mode = df_merged.groupby('Ship Mode')['Order ID'].nunique().reset_index()
shipments_by_mode.rename(columns={'Order ID': 'Number of Orders'}, inplace=True)
display(shipments_by_mode)

        Ship Mode  Number of Orders
0     First Class              1312
1        Same Day               442
2    Second Class              1653
3  Standard Class              5142

 Route Analysis: Factory to Customer Region

In [ ]:
route_region_analysis = df_merged.groupby(['Factory', 'Region']).agg(
    Total_Shipments=('Order ID', 'nunique'),
    Average_Shipping_Lead_Time=('Lead Time', 'mean'),
    Lead_Time_Variability=('Lead Time', 'std')
).reset_index()
display(route_region_analysis.head())

,Factory,Region,Total_Shipments,Average_Shipping_Lead_Time,Lead_Time_Variability
0,Lot's O' Nuts,Atlantic,1378,1326 days 19:48:35.111378688,255 days 23:45:39.903954604
1,Lot's O' Nuts,Gulf,745,1313 days 23:24:40.936454848,266 days 14:06:34.977844756
2,Lot's O' Nuts,Interior,1113,1324 days 04:42:19.894019680,258 days 09:52:28.258112712
3,Lot's O' Nuts,Pacific,1524,1317 days 12:40:06.618863760,266 days 16:08:41.264866764
4,Secret Factory,Atlantic,70,1349 days 06:00:00,280 days 17:13:10.154942672

Route Analysis: Factory to Customer State/Province

In [ ]:
route_state_analysis = df_merged.groupby(['Factory', 'State/Province']).agg(
    Total_Shipments=('Order ID', 'nunique'),
    Average_Shipping_Lead_Time=('Lead Time', 'mean'),
    Lead_Time_Variability=('Lead Time', 'std')
).reset_index()
display(route_state_analysis.head())

,Factory,State/Province,Total_Shipments,Average_Shipping_Lead_Time,Lead_Time_Variability
0,Lot's O' Nuts,Alabama,30,1295 days 04:56:28.235294112,253 days 01:41:16.642641672
1,Lot's O' Nuts,Alberta,12,1273 days 21:00:00,266 days 22:11:10.536614560
2,Lot's O' Nuts,Arizona,94,1306 days 04:45:24.324324320,253 days 21:37:39.828353616
3,Lot's O' Nuts,Arkansas,25,1285 days 08:30:58.064516128,274 days 12:41:55.784071776
4,Lot's O' Nuts,British Columbia,18,1273 days 18:40:00,307 days 01:59:11.670480360

### Route Ranking by Average Lead Time (Factory to Region)

In [ ]:
# Sort routes by Average_Shipping_Lead_Time from fastest to slowest
ranked_region_routes = route_region_analysis.sort_values(by='Average_Shipping_Lead_Time', ascending=True)
display(ranked_region_routes.head())

,Factory,Region,Total_Shipments,Average_Shipping_Lead_Time,Lead_Time_Variability
9,Sugar Shack,Gulf,4,1091 days 06:00:00,210 days 10:44:44.475071328
14,The Other Factory,Interior,11,1206 days 15:16:21.818181824,274 days 10:16:39.249020180
13,The Other Factory,Gulf,19,1272 days 15:09:28.421052624,272 days 17:34:31.483063944
12,The Other Factory,Atlantic,37,1282 days 17:41:03.157894736,262 days 04:05:42.951901732
6,Secret Factory,Interior,45,1289 days 02:08:00,311 days 05:24:49.266562620

### Top 10 Most Efficient Routes (Factory to Region)

In [ ]:
top_10_efficient_regions = ranked_region_routes.head(10)
display(top_10_efficient_regions)

,Factory,Region,Total_Shipments,Average_Shipping_Lead_Time,Lead_Time_Variability
9,Sugar Shack,Gulf,4,1091 days 06:00:00,210 days 10:44:44.475071328
14,The Other Factory,Interior,11,1206 days 15:16:21.818181824,274 days 10:16:39.249020180
13,The Other Factory,Gulf,19,1272 days 15:09:28.421052624,272 days 17:34:31.483063944
12,The Other Factory,Atlantic,37,1282 days 17:41:03.157894736,262 days 04:05:42.951901732
6,Secret Factory,Interior,45,1289 days 02:08:00,311 days 05:24:49.266562620
15,The Other Factory,Pacific,31,1307 days 05:15:00,251 days 10:01:55.955510756
7,Secret Factory,Pacific,63,1307 days 17:31:25.714285712,276 days 04:19:27.349055136
17,Wicked Choccy's,Gulf,547,1309 days 02:42:53.755656112,259 days 21:39:35.403103084
1,Lot's O' Nuts,Gulf,745,1313 days 23:24:40.936454848,266 days 14:06:34.977844756
16,Wicked Choccy's,Atlantic,973,1315 days 23:13:04.962406016,255 days 09:23:07.282740048

### Bottom 10 Least Efficient Routes (Factory to Region)

In [ ]:
bottom_10_inefficient_regions = ranked_region_routes.tail(10)
display(bottom_10_inefficient_regions)

,Factory,Region,Total_Shipments,Average_Shipping_Lead_Time,Lead_Time_Variability
3,Lot's O' Nuts,Pacific,1524,1317 days 12:40:06.618863760,266 days 16:08:41.264866764
10,Sugar Shack,Interior,8,1318 days 15:00:00,235 days 06:10:27.954471604
2,Lot's O' Nuts,Interior,1113,1324 days 04:42:19.894019680,258 days 09:52:28.258112712
18,Wicked Choccy's,Interior,802,1324 days 13:14:16.421052624,266 days 07:49:24.887098488
0,Lot's O' Nuts,Atlantic,1378,1326 days 19:48:35.111378688,255 days 23:45:39.903954604
19,Wicked Choccy's,Pacific,1123,1329 days 02:25:55.886736208,266 days 05:15:15.631119392
5,Secret Factory,Gulf,35,1332 days 12:58:22.702702704,304 days 19:56:04.549063560
4,Secret Factory,Atlantic,70,1349 days 06:00:00,280 days 17:13:10.154942672
8,Sugar Shack,Atlantic,18,1375 days 09:20:00,274 days 14:33:57.416753272
11,Sugar Shack,Pacific,3,1516 days 16:00:00,210 days 03:43:55.025906052

Route Ranking by Average Lead Time (Factory to State/Province)

In [ ]:
# Sort routes by Average_Shipping_Lead_Time from fastest to slowest
ranked_state_routes = route_state_analysis.sort_values(by='Average_Shipping_Lead_Time', ascending=True)
display(ranked_state_routes.head())

,Factory,State/Province,Total_Shipments,Average_Shipping_Lead_Time,Lead_Time_Variability
76,Secret Factory,Nebraska,1,906 days 00:00:00,NaT
80,Secret Factory,New Mexico,2,906 days 00:00:00,2 days 19:52:56.103578070
121,The Other Factory,Louisiana,1,907 days 00:00:00,NaT
115,The Other Factory,Connecticut,2,907 days 12:00:00,2 days 02:54:42.077683553
158,Wicked Choccy's,Maine,2,908 days 00:00:00,0 days 00:00:00

Top 10 Most Efficient Routes (Factory to State/Province)

In [ ]:
top_10_efficient_states = ranked_state_routes.head(10)
display(top_10_efficient_states)

,Factory,State/Province,Total_Shipments,Average_Shipping_Lead_Time,Lead_Time_Variability
76,Secret Factory,Nebraska,1,906 days 00:00:00,NaT
80,Secret Factory,New Mexico,2,906 days 00:00:00,2 days 19:52:56.103578070
121,The Other Factory,Louisiana,1,907 days 00:00:00,NaT
115,The Other Factory,Connecticut,2,907 days 12:00:00,2 days 02:54:42.077683553
158,Wicked Choccy's,Maine,2,908 days 00:00:00,0 days 00:00:00
75,Secret Factory,Mississippi,1,908 days 00:00:00,NaT
70,Secret Factory,Louisiana,2,908 days 12:00:00,0 days 16:58:14.025894517
64,Secret Factory,Delaware,1,909 days 00:00:00,NaT
88,Secret Factory,South Carolina,1,909 days 00:00:00,NaT
74,Secret Factory,Minnesota,1,909 days 00:00:00,NaT

 Bottom 10 Least Efficient Routes (Factory to State/Province)

In [ ]:
bottom_10_inefficient_states = ranked_state_routes.tail(10)
display(bottom_10_inefficient_states)

,Factory,State/Province,Total_Shipments,Average_Shipping_Lead_Time,Lead_Time_Variability
69,Secret Factory,Kentucky,2,1637 days 12:00:00,0 days 16:58:14.025894517
110,Sugar Shack,Washington,1,1638 days 00:00:00,NaT
125,The Other Factory,Nevada,1,1638 days 00:00:00,NaT
63,Secret Factory,Connecticut,1,1638 days 00:00:00,NaT
97,Sugar Shack,California,1,1638 days 00:00:00,NaT
37,Lot's O' Nuts,North Dakota,4,1638 days 04:48:00,1 days 15:26:09.686905339
194,Wicked Choccy's,West Virginia,2,1639 days 00:00:00,0 days 00:00:00
78,Secret Factory,New Hampshire,1,1641 days 00:00:00,NaT
98,Sugar Shack,Connecticut,1,1641 days 00:00:00,NaT
103,Sugar Shack,New Jersey,1,1642 days 00:00:00,NaT

Performance Comparison Across Ship Modes

In [ ]:
ship_mode_performance = df_merged.groupby('Ship Mode').agg(
    Total_Shipments=('Order ID', 'nunique'),
    Average_Shipping_Lead_Time=('Lead Time', 'mean'),
    Lead_Time_Variability=('Lead Time', 'std')
).reset_index()
display(ship_mode_performance.sort_values(by='Average_Shipping_Lead_Time'))

,Ship Mode,Total_Shipments,Average_Shipping_Lead_Time,Lead_Time_Variability
3,Standard Class,5142,1314 days 08:01:52.941176464,262 days 09:36:10.041529276
2,Second Class,1653,1323 days 20:17:20.525517936,261 days 19:31:32.398991320
1,Same Day,442,1333 days 10:37:04.497257776,253 days 19:31:15.513476732
0,First Class,1312,1338 days 06:37:12.558139536,265 days 15:10:16.909276700

#Geographic Bottleneck Analysis: High Average Lead Time

Regions with Highest Average Lead Time

In [ ]:
bottom_10_inefficient_regions.tail(1)

,Factory,Region,Total_Shipments,Average_Shipping_Lead_Time,Lead_Time_Variability
11,Sugar Shack,Pacific,3,1516 days 16:00:00,210 days 03:43:55.025906052

 States/Provinces with Highest Average Lead Time

In [ ]:
bottom_10_inefficient_states.tail(1)

,Factory,State/Province,Total_Shipments,Average_Shipping_Lead_Time,Lead_Time_Variability
103,Sugar Shack,New Jersey,1,1642 days,NaT

Geographic Bottleneck Analysis: High Shipment Volume + Poor Performance (Congestion-Prone)

In [ ]:
# Calculate mean for Total_Shipments and Average_Shipping_Lead_Time for regions
mean_shipments_region = route_region_analysis['Total_Shipments'].mean()
mean_lead_time_region = route_region_analysis['Average_Shipping_Lead_Time'].mean()

# Filter for regions with high shipment volume and high average lead time
congestion_prone_regions = route_region_analysis[
    (route_region_analysis['Total_Shipments'] > mean_shipments_region) &
    (route_region_analysis['Average_Shipping_Lead_Time'] > mean_lead_time_region)
].sort_values(by='Average_Shipping_Lead_Time', ascending=False)

print(f"Mean Total Shipments (Regions): {mean_shipments_region:.2f}")
print(f"Mean Average Shipping Lead Time (Regions): {mean_lead_time_region}")
print("\nCongestion-Prone Regions (High Volume + High Lead Time):")
display(congestion_prone_regions)

Mean Total Shipments (Regions): 427.45
Mean Average Shipping Lead Time (Regions): 1310 days 13:13:34.770034272

Congestion-Prone Regions (High Volume + High Lead Time):

,Factory,Region,Total_Shipments,Average_Shipping_Lead_Time,Lead_Time_Variability
19,Wicked Choccy's,Pacific,1123,1329 days 02:25:55.886736208,266 days 05:15:15.631119392
0,Lot's O' Nuts,Atlantic,1378,1326 days 19:48:35.111378688,255 days 23:45:39.903954604
18,Wicked Choccy's,Interior,802,1324 days 13:14:16.421052624,266 days 07:49:24.887098488
2,Lot's O' Nuts,Interior,1113,1324 days 04:42:19.894019680,258 days 09:52:28.258112712
3,Lot's O' Nuts,Pacific,1524,1317 days 12:40:06.618863760,266 days 16:08:41.264866764
16,Wicked Choccy's,Atlantic,973,1315 days 23:13:04.962406016,255 days 09:23:07.282740048
1,Lot's O' Nuts,Gulf,745,1313 days 23:24:40.936454848,266 days 14:06:34.977844756

In [ ]:
# Calculate mean for Total_Shipments and Average_Shipping_Lead_Time for states
mean_shipments_state = route_state_analysis['Total_Shipments'].mean()
mean_lead_time_state = route_state_analysis['Average_Shipping_Lead_Time'].mean()

# Filter for states with high shipment volume and high average lead time
congestion_prone_states = route_state_analysis[
    (route_state_analysis['Total_Shipments'] > mean_shipments_state) &
    (route_state_analysis['Average_Shipping_Lead_Time'] > mean_lead_time_state)
].sort_values(by='Average_Shipping_Lead_Time', ascending=False)

print(f"Mean Total Shipments (States): {mean_shipments_state:.2f}")
print(f"Mean Average Shipping Lead Time (States): {mean_lead_time_state}")
print("\nCongestion-Prone States (High Volume + High Lead Time):")
display(congestion_prone_states)

Mean Total Shipments (States): 43.62
Mean Average Shipping Lead Time (States): 1314 days 01:04:54.635398160

Congestion-Prone States (High Volume + High Lead Time):

,Factory,State/Province,Total_Shipments,Average_Shipping_Lead_Time,Lead_Time_Variability
153,Wicked Choccy's,Indiana,44,1402 days 11:06:40,257 days 18:22:05.341672272
188,Wicked Choccy's,Tennessee,56,1393 days 18:16:07.164179104,241 days 08:35:55.673182156
48,Lot's O' Nuts,Tennessee,88,1390 days 23:07:09.357798160,257 days 17:11:30.173753828
193,Wicked Choccy's,Washington,187,1375 days 17:22:32.036199088,270 days 19:16:17.680820548
21,Lot's O' Nuts,Maryland,44,1370 days 16:00:00,221 days 22:01:05.736885832
55,Lot's O' Nuts,Wisconsin,44,1367 days 15:18:37.241379312,242 days 09:06:21.112211820
14,Lot's O' Nuts,Indiana,74,1366 days 18:56:00,236 days 02:56:52.108032520
174,Wicked Choccy's,North Carolina,91,1352 days 18:17:49.306930688,261 days 10:34:56.862756224
6,Lot's O' Nuts,Colorado,82,1347 days 12:48:55.922330096,252 days 15:38:56.579230008
150,Wicked Choccy's,Georgia,55,1346 days 03:41:32.307692304,251 days 21:12:12.837441312
53,Lot's O' Nuts,Washington,230,1343 days 23:06:28.104089216,274 days 23:24:27.235900268
181,Wicked Choccy's,Pennsylvania,188,1339 days 05:17:10.837004400,263 days 16:09:54.377572180
32,Lot's O' Nuts,New Jersey,53,1335 days 15:52:36.923076928,278 days 16:02:23.984663308
171,Wicked Choccy's,New Jersey,49,1335 days 09:21:21.355932208,216 days 13:47:24.431369408
38,Lot's O' Nuts,Ohio,218,1334 days 02:44:53.129770992,260 days 10:39:17.426155060
34,Lot's O' Nuts,New York,544,1330 days 12:23:26.511627904,249 days 06:19:33.061341744
11,Lot's O' Nuts,Georgia,88,1329 days 13:31:38.181818176,243 days 10:35:50.137354428
152,Wicked Choccy's,Illinois,183,1329 days 03:05:08.571428576,266 days 06:09:15.432956412
17,Lot's O' Nuts,Kentucky,63,1325 days 09:39:44.415584416,276 days 06:28:27.299812072
156,Wicked Choccy's,Kentucky,45,1323 days 19:26:53.793103456,268 days 23:59:03.407996176
141,Wicked Choccy's,Arizona,88,1322 days 02:44:34.285714288,273 days 04:52:39.255664728
144,Wicked Choccy's,California,689,1320 days 07:50:40.097205344,262 days 12:00:25.141484900
13,Lot's O' Nuts,Illinois,235,1319 days 22:22:55.280898880,268 days 09:18:37.907536992
145,Wicked Choccy's,Colorado,49,1319 days 20:13:42.857142864,256 days 04:51:07.950967240
10,Lot's O' Nuts,Florida,176,1318 days 14:35:01.435406704,283 days 04:24:39.142572204
5,Lot's O' Nuts,California,944,1316 days 21:50:43.200000,265 days 08:58:19.903669596
189,Wicked Choccy's,Texas,326,1315 days 14:35:52.577319584,272 days 22:34:10.428357596
42,Lot's O' Nuts,Pennsylvania,270,1315 days 01:31:21.570996976,260 days 11:36:54.566136600
36,Lot's O' Nuts,North Carolina,120,1314 days 04:41:57.482517488,249 days 07:21:17.601954312

### Shipping Efficiency: Standard vs. Expedited

In [ ]:
# Define Standard and Expedited Shipping categories
standard_shipping_modes = ['Standard Class']
expedited_shipping_modes = ['First Class', 'Same Day', 'Second Class']

# Filter for Standard Shipping performance
standard_shipping_performance = ship_mode_performance[ship_mode_performance['Ship Mode'].isin(standard_shipping_modes)]

# Filter for Expedited Shipping performance
expedited_shipping_performance = ship_mode_performance[ship_mode_performance['Ship Mode'].isin(expedited_shipping_modes)]

# Calculate aggregated performance for Expedited Shipping
# We'll take a weighted average for lead time if there were volume differences, but a simple mean for illustration
expedited_avg_lead_time = expedited_shipping_performance['Average_Shipping_Lead_Time'].mean()
expedited_avg_variability = expedited_shipping_performance['Lead_Time_Variability'].mean()
expedited_total_shipments = expedited_shipping_performance['Total_Shipments'].sum()

print("**Standard Shipping Performance:**")
display(standard_shipping_performance)

print("**Expedited Shipping Performance (Aggregated):**")
print(f"Total Shipments: {expedited_total_shipments}")
print(f"Average Shipping Lead Time: {expedited_avg_lead_time}")
print(f"Lead Time Variability: {expedited_avg_variability}")

**Standard Shipping Performance:**

,Ship Mode,Total_Shipments,Average_Shipping_Lead_Time,Lead_Time_Variability
3,Standard Class,5142,1314 days 08:01:52.941176464,262 days 09:36:10.041529276

**Expedited Shipping Performance (Aggregated):**
Total Shipments: 3407
Average Shipping Lead Time: 1331 days 20:30:32.526971760
Lead Time Variability: 260 days 10:04:21.607248252

### Evaluation of Cost-Time Tradeoffs
Based on the analysis of shipping modes, we can observe the following cost-time tradeoffs:


Standard Class (Standard Shipping)  This mode handles the vast majority of shipments and typically has the lowest *implied* cost, as it also has a relatively shorter average lead time compared to 'First Class' and 'Same Day', but slightly longer than 'Second Class'. Its lead time variability is also in a similar range to other modes.

Expedited Shipping (First Class, Same Day, Second Class) These modes generally offer faster delivery times (or specific delivery windows like 'Same Day'), but usually come at a higher cost. We see that 'Same Day' and 'First Class' actually have longer average lead times than 'Standard Class' in this dataset, which is counter-intuitive for 'expedited' services.

Given the current data, 'Standard Class' appears to be the most efficient in terms of lead time for its likely lower cost, although the specific cost data for each shipping mode is not available to confirm direct cost-time tradeoffs. The 'Same Day' option, despite its name, shows a longer average lead time than 'Standard Class', which is a significant point for further investigation if expedited services are a business priority.

In [ ]:
df=pd.read_csv(r"C:\Users\I SKY\Downloads/Nassau Candy Distributor.csv")
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [ ]:
import sys
!{sys.executable} -m pip install plotly

'c:\Users\I' is not recognized as an internal or external command,
operable program or batch file.

In [ ]:
import plotly.express as px

In [ ]:
df['Order Date'] = pd.to_datetime(df['Order Date'], format='mixed', dayfirst=True)
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='mixed', dayfirst=True)

import streamlit as st
import pandas as pd
import plotly.express as px

# -------------------------------------------------------------------------
# PRE-REQUISITES & ASSUMPTIONS
# The variable `df` is expected to be loaded before this code runs.
# We assume the following column names exist in your `df`:
# 'Order Date', 'Ship Date', 'State', 'Region', 'Ship Mode', 'Route', 
# 'Lead Time', and 'Order ID'. Modify these string keys if yours differ.
# -------------------------------------------------------------------------

st.set_page_config(page_title="Shipping Efficiency Dashboard", layout="wide")
st.title("📦 Shipping & Route Efficiency Dashboard")

# --- DATA PREPARATION ---
# Ensure dates are datetime objects for the filter
df['Order Date'] = pd.to_datetime(df['Order Date'], format='mixed', dayfirst=True)
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='mixed', dayfirst=True)

# If Lead Time doesn't exist, calculate it (Ship Date - Order Date)
if 'Lead Time' not in df.columns:
    df['Lead Time'] = (df['Ship Date'] - df['Order Date']).dt.days

# --- GLOBAL FILTERS (SIDEBAR) ---
st.sidebar.header("Global Filters")

# 1. Date Range Filter
min_date = df['Order Date'].min().date()
max_date = df['Order Date'].max().date()
date_selection = st.sidebar.date_input(
    "Select Date Range",
    value=(min_date, max_date),
    min_value=min_date,
    max_value=max_date
)

# Handle cases where the user hasn't selected the end date yet
if len(date_selection) == 2:
    start_date, end_date = date_selection
else:
    start_date = end_date = date_selection[0]

# 2. Region / State Selector
all_states = sorted(df['State'].dropna().unique())
selected_states = st.sidebar.multiselect(
    "Select Region / State(s)",
    options=all_states,
    default=all_states
)

# 3. Ship Mode Filter
all_modes = df['Ship Mode'].dropna().unique()
selected_modes = st.sidebar.multiselect(
    "Select Ship Mode(s)",
    options=all_modes,
    default=all_modes
)

# 4. Lead-time Threshold Slider
min_lead = int(df['Lead Time'].min())
max_lead = int(df['Lead Time'].max())
lead_threshold = st.sidebar.slider(
    "Max Lead-Time Threshold (Days)",
    min_value=min_lead,
    max_value=max_lead,
    value=max_lead
)

# --- APPLY FILTERS TO DATASET ---
mask = (
    (df['Order Date'].dt.date >= start_date) &
    (df['Order Date'].dt.date <= end_date) &
    (df['State'].isin(selected_states)) &
    (df['Ship Mode'].isin(selected_modes)) &
    (df['Lead Time'] <= lead_threshold)
)
filtered_df = df[mask]

# Stop execution if filters result in an empty dataset
if filtered_df.empty:
    st.warning("No data available with the current filter settings. Please adjust your filters.")
    st.stop()

# --- LAYOUT & SECTIONS ---

st.markdown("---")

# ==========================================
# SECTION 1: Route Efficiency Overview
# ==========================================
st.header("1. Route Efficiency Overview")
col1, col2 = st.columns(2)

with col1:
    st.subheader("Average Lead Time by Route")
    # Aggregate data by Route
    route_avg_time = filtered_df.groupby('Route', as_index=False)['Lead Time'].mean().sort_values(by='Lead Time')
    fig_route = px.bar(
        route_avg_time.head(10), # Showing top 10 for readability
        x='Lead Time', y='Route', orientation='h',
        title="Top 10 Fastest Routes (Avg Lead Time)",
        color='Lead Time', color_continuous_scale='Viridis_r'
    )
    st.plotly_chart(fig_route, use_container_width=True)

with col2:
    st.subheader("Route Performance Leaderboard")
    # Provide a detailed table grouped by route
    leaderboard = filtered_df.groupby('Route').agg(
        Total_Orders=('Order ID', 'nunique'),
        Avg_Lead_Time=('Lead Time', 'mean'),
        Max_Lead_Time=('Lead Time', 'max')
    ).reset_index().sort_values(by='Avg_Lead_Time')
    st.dataframe(leaderboard.style.format({"Avg_Lead_Time": "{:.2f}"}), use_container_width=True, height=350)

st.markdown("---")

# ==========================================
# SECTION 2: Geographic Shipping Map
# ==========================================
st.header("2. Geographic Shipping Map")
col3, col4 = st.columns(2)

with col3:
    st.subheader("US Heatmap of Shipping Efficiency")
    # Assumes 'State' contains 2-letter US State codes (e.g., 'CA', 'TX')
    state_perf = filtered_df.groupby('State', as_index=False)['Lead Time'].mean()
    fig_map = px.choropleth(
        state_perf,
        locations='State',
        locationmode="USA-states",
        color='Lead Time',
        scope="usa",
        color_continuous_scale="RdYlGn_r", # Green is good (low time), Red is bad (high time)
        title="Average Lead Time by State"
    )
    st.plotly_chart(fig_map, use_container_width=True)

with col4:
    st.subheader("Regional Bottlenecks")
    # Highlight the top 10 states with the highest average lead time
    bottlenecks = state_perf.sort_values(by='Lead Time', ascending=False).head(10)
    fig_bottleneck = px.bar(
        bottlenecks,
        x='State', y='Lead Time',
        title="Top 10 Slowest States (Bottlenecks)",
        color='Lead Time', color_continuous_scale='Reds'
    )
    st.plotly_chart(fig_bottleneck, use_container_width=True)

st.markdown("---")

# ==========================================
# SECTION 3: Ship Mode Comparison
# ==========================================
st.header("3. Ship Mode Comparison")

st.subheader("Lead Time Distribution by Shipping Method")
# A Box plot is excellent for showing distributions and outliers across categories
fig_ship_mode = px.box(
    filtered_df,
    x='Ship Mode', y='Lead Time',
    color='Ship Mode',
    title="Lead Time Variability per Shipping Mode"
)
st.plotly_chart(fig_ship_mode, use_container_width=True)

st.markdown("---")

# ==========================================
# SECTION 4: Route Drill-Down
# ==========================================
st.header("4. Route Drill-Down")

# Allow user to pick a specific route from the filtered data for deep diving
specific_route = st.selectbox("Select a Route for Drill-Down", options=filtered_df['Route'].unique())
drill_down_df = filtered_df[filtered_df['Route'] == specific_route]

col5, col6 = st.columns([1, 2])

with col5:
    st.subheader("State-Level Insights")
    # Breakdown of performance inside this specific route by State
    state_breakdown = drill_down_df.groupby('State').agg(
        Orders=('Order ID', 'count'),
        Avg_Time=('Lead Time', 'mean')
    ).reset_index()
    st.dataframe(state_breakdown, use_container_width=True)

with col6:
    st.subheader("Order-Level Shipment Timelines")
    # Gantt chart (timeline) for individual orders on this route
    # Taking top 20 to keep the chart clean, but you can adjust this
    timeline_df = drill_down_df.head(20) 
    
    if not timeline_df.empty:
        fig_timeline = px.timeline(
            timeline_df,
            x_start="Order Date",
            x_end="Ship Date",
            y="Order ID",
            color="Ship Mode",
            title=f"Shipment Timeline for top recent orders on route: {specific_route}"
        )
        # Update y-axis to show orders from top to bottom
        fig_timeline.update_yaxes(autorange="reversed") 
        st.plotly_chart(fig_timeline, use_container_width=True)
    else:
        st.info("No timeline data available for this route.")

2026-05-03 18:55:22.213 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-03 18:55:22.231 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-03 18:55:22.234 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-03 18:55:22.241 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-03 18:55:22.399 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-03 18:55:22.405 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-03 18:55:22.407 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-03 18:55:22.420 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-03 18:55:22.424 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-03 18:55:22.430 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-03 18:55:22.441 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-03 18:55:22.446 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-03 18:55:22.448 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

KeyError: 'State'